### ISSUE TITLE
Need to increase test_name size

### ISSUE THREAD

**Issue by dimtruck** [rackerlabs/tetra#27]
We have test names that include stack traces.  That blows the 256 character limit out of the water:

```
tetra-db     | ERROR:  value too long for type character varying(256)
tetra-db     | STATEMENT:  INSERT INTO results (project_id, build_id, test_name, timestamp, result, result_message) VALUES (2, 8081, 'test_yaml_check_3.#367 { "err": { "arguments": undefined, "message": "file has no content", "stack": "Error: file has no content\n at ConfigState.parseFile (/opt/ele/lib/agent_endpoint/config_file.js:185:13)\n at /opt/ele/lib/agent_endpoint/config_file.js:652:17\n at Function._.each._.forEach (/opt/ele/node_modules/underscore/underscore.js:87:22)\n at Object.post (/opt/ele/lib/agent_endpoint/config_file.js:651:5)\n at /opt/ele/tests/integration/agent-config.js:90:19\n at /opt/ele/node_modules/async/lib/async.js:157:25\n at /opt/ele/tests/integration/agent-config.js:84:9\n at fs.js:271:14\n at /opt/ele/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:90:5\n at Object.oncomplete (fs.js:107:15)", "type": undefined }, "handle": "filesystem.yaml", "location": "parsing", "success": false, "type": "file" }', 1469245686.411962, 'passed', NULL)
```

**Comment by pglass** [comment]
Do you prefer to keep the whole test name or truncate it to some limit?

**Comment by dimtruck** [comment]
@pglass we LITERALLY just discussed this :).  truncated at 256 should be fine.
